title:             Katazana
email:             zulfanlife@gmail.com
description:       Tempat Download Aplikasi
author:            Blogger Indonesia
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://katazana.github.io"

# Social Profiles
twitter_username:  Tidak Ada
github_username:   ZulfanLife
facebook_username: Tidak Ada

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
